on:
  workflow_call: 
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        type: string
      checkout-ref:
        description: 'The commit SHA to checkout' 
        required: true
        type: string
    
jobs:
  push-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Lowercase Tag
        id: lowercase_tag
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          echo "repo_owner=$(echo $REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "container_name=$(echo 'AppSettings.Merge' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          
      - name: Build and push Docker image
        # Using commit from v2 era - AC9327EAE2B366085AC7F6A2D02DF8AA8EAD720A  
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: ./src/BlazorMerge/Dockerfile
          push: true
          tags: ghcr.io/${{ env.repo_owner }}/${{ env.container_name }}:${{ inputs.version }}